import httpx
from database import settings

# Resend free-tier "from" address (works without a custom domain during dev)
_FROM = "OptiFi <onboarding@resend.dev>"


async def send_email(to_email: str, subject: str, html_body: str) -> bool:
    """Send email via Resend API. Returns True on success, False if not configured or on error."""
    if not settings.RESEND_API_KEY:
        return False
    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            response = await client.post(
                "https://api.resend.com/emails",
                headers={
                    "Authorization": f"Bearer {settings.RESEND_API_KEY}",
                    "Content-Type": "application/json",
                },
                json={
                    "from": _FROM,
                    "to": [to_email],
                    "subject": subject,
                    "html": html_body,
                },
            )
            return response.status_code in (200, 201)
    except Exception:
        return False


def weekly_review_html(summary: str, week_start: str, week_end: str) -> str:
    lines = []
    for line in summary.split("\n"):
        if line.startswith("## "):
            lines.append(f"<h3 style='color:#e5e5e5;margin:20px 0 6px'>{line[3:]}</h3>")
        elif line.startswith("**") and line.endswith("**"):
            lines.append(f"<p style='font-weight:600;color:#e5e5e5;margin:12px 0 4px'>{line[2:-2]}</p>")
        elif line.startswith("- ") or line.startswith("• "):
            lines.append(f"<p style='color:#aaa;margin:2px 0 2px 12px'>• {line[2:]}</p>")
        elif line.strip():
            lines.append(f"<p style='color:#aaa;margin:6px 0;line-height:1.6'>{line}</p>")
    body_html = "\n".join(lines)

    return f"""
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="background:#0f0f0f;color:#e5e5e5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;margin:0;padding:0">
  <div style="max-width:600px;margin:32px auto;background:#1a1a1a;border:1px solid #2a2a2a;border-radius:12px;overflow:hidden">
    <div style="background:linear-gradient(135deg,#6366f1,#8b5cf6);padding:32px">
      <h1 style="margin:0;font-size:22px;color:white">Your Weekly Financial Review</h1>
      <p style="margin:6px 0 0;font-size:13px;color:rgba(255,255,255,0.8)">{week_start} — {week_end}</p>
    </div>
    <div style="padding:28px">
      {body_html}
    </div>
    <div style="padding:16px 28px;border-top:1px solid #2a2a2a;font-size:11px;color:#555;text-align:center">
      Generated by OptiFi · Your AI Financial Advisor
    </div>
  </div>
</body>
</html>
"""


def tax_report_html(analysis: str, user_email: str, tax_year: int) -> str:
    lines = []
    for line in analysis.split("\n"):
        if line.startswith("## "):
            lines.append(f"<h3 style='color:#e5e5e5;margin:20px 0 6px'>{line[3:]}</h3>")
        elif line.startswith("**") and line.endswith("**"):
            lines.append(f"<p style='font-weight:600;color:#e5e5e5;margin:12px 0 4px'>{line[2:-2]}</p>")
        elif line.startswith("- ") or line.startswith("• "):
            lines.append(f"<p style='color:#aaa;margin:2px 0 2px 12px'>• {line[2:]}</p>")
        elif line.strip():
            lines.append(f"<p style='color:#aaa;margin:6px 0;line-height:1.6'>{line}</p>")
    body_html = "\n".join(lines)

    return f"""
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="background:#0f0f0f;color:#e5e5e5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;margin:0;padding:0">
  <div style="max-width:600px;margin:32px auto;background:#1a1a1a;border:1px solid #2a2a2a;border-radius:12px;overflow:hidden">
    <div style="background:linear-gradient(135deg,#22c55e,#16a34a);padding:32px">
      <h1 style="margin:0;font-size:22px;color:white">Your {tax_year} Tax Savings Report</h1>
      <p style="margin:6px 0 0;font-size:13px;color:rgba(255,255,255,0.8)">Potential deductions identified from your transactions</p>
    </div>
    <div style="padding:28px">
      {body_html}
    </div>
    <div style="padding:16px 28px;border-top:1px solid #2a2a2a;font-size:11px;color:#555;text-align:center">
      Generated by OptiFi · Consult a tax professional for personalized advice.
    </div>
  </div>
</body>
</html>
"""
